### ISSUE TITLE
Add MobileOne model implementation and checkpoints

### ISSUE THREAD

**Issue by lzrwch** [Deeplite/deeplite-torch-zoo#242]

**Comment by shahrukh-dl** [comment]
# Accuracy computed using deeplite-torch-zoo from mobileone checkpoints
    # mobileone_s0 {'acc': 0.713699996471405, 'acc_top5': 0.8986600041389465}
    # mobileone_s1 {'acc': 0.7576599717140198, 'acc_top5': 0.9276599884033203}
    # mobileone_s2 {'acc': 0.7739399671554565, 'acc_top5': 0.9362799525260925}
    # mobileone_s3 {'acc': 0.779259979724884, 'acc_top5': 0.9388999938964844}
    # mobileone_s4 {'acc': 0.792959988117218, 'acc_top5': 0.9438599944114685}
