### ISSUE TITLE
Remove **kwargs from the deepest functions

### ISSUE THREAD

**Issue by olivier-dl** [Deeplite/deeplite-torch-zoo#30]
A lot the final loading functions have a dangerous `**kwargs` that absorbs everything and is not used. This is error prone when doing typos on real arguments.

Those `**kwargs` should be removed.

ex.: https://github.com/Deeplite/deeplite-torch-zoo/blob/master/deeplite_torch_zoo/wrappers/datasets/classification/cifar100.py#L14

**Comment by ehsab** [comment]
@ahmed-deeplite @yasseridris could you please confirm that we can remove these kwargs from zoo?

**Comment by ahmed-deeplite** [comment]
No, we can't. In order to allow for flexible signature for different data-loaders we need to keep `**kwargs`  otherwise we will have to write all possible argument names in every data-loader function.

**Comment by olivier-dl** [comment]
I don't understand. It makes sense on the top level call to have **kwargs. I dont see why this `get_cifar100` needs it. It does not use it, it does not transfer those words to another function and it does not implement any class method interface.

**Comment by ahmed-deeplite** [comment]
For instance in training loops, if you need to support different datasets and you need to call the wrapper function once. you might need to pass extra arguments that are not part of the function that you actually need to call.

**Comment by olivier-dl** [comment]
I feel this will become a church debate :D

I personally think this burden is on the caller, not the callee. 

If everyone here disagree, I would at least like to have some logger.warning at those deepest calls if `kwargs` is not an empty dict. At least there would be some information to the caller of potential typos and errors.

**Comment by ahmed-deeplite** [comment]
I don’t mind adding theses warnings messages

**Comment by ahmed-deeplite** [comment]
warning is printed when extra unused arguments are passed
